DROP TABLE IF EXISTS Genders;
DROP TABLE IF EXISTS Local_status;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Summaries;
DROP TABLE IF EXISTS Campaigns;
DROP TABLE IF EXISTS MAINCONF;

CREATE TABLE Local_status (
	PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL
) ENGINE = INNODB, COLLATE = utf8_general_ci;

INSERT INTO `Local_status` (`PK`, `TITLE`) VALUES
(1, 'Dead'),
(2, 'Alive'),
(3, 'CreatePending'),
(4, 'DeletePending'),
(5, 'CreateFail'),
(6, 'DeleteFail');

CREATE TABLE Genders (
	PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(10) NOT NULL
) ENGINE = INNODB, COLLATE = utf8_general_ci;

INSERT INTO `Genders` (`PK`, `TITLE`) VALUES
(3, 'All'),
(1, 'Male'),
(2, 'Female');

UPDATE `Genders` SET `PK` = 0 WHERE `TITLE`='All';

CREATE TABLE MAINCONF (
	PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        CONF_TITLE VARCHAR(20) NOT NULL,
        MAX_MONITOR_THREAD INT(3) NOT NULL,
        MON_LOAD_ITERATION INT(3) NOT NULL,
        MON_CHECK_ITERATION INT(4) NOT NULL,
        MON_TIMEOUT_LIMIT INT(2) NOT NULL,
        MON_INIT_RETRY_WAITING_TIME INT(3) NOT NULL,
        MON_INIT_RETRY_COMMON_RATIO INT(2) NOT NULL
) ENGINE = INNODB, COLLATE = utf8_general_ci;

INSERT INTO `MAINCONF` (`PK`, `CONF_TITLE`, `MAX_MONITOR_THREAD`, `MON_LOAD_ITERATION`, `MON_CHECK_ITERATION`, `MON_TIMEOUT_LIMIT`, `MON_INIT_RETRY_WAITING_TIME`, `MON_INIT_RETRY_COMMON_RATIO`) VALUES
(1, 'Default', 2, 1, 60, 1, 10, 2);

CREATE TABLE Accounts (
	PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        FI_ID INT NOT NULL UNIQUE,
        USERNAME VARCHAR(20) NOT NULL,
        PSWD VARCHAR(32) NOT NULL COLLATE latin1_swedish_ci,
        ACTIVE BOOLEAN NOT NULL DEFAULT 0,
        BUDGET_LIMIT_THRESHOLD FLOAT DEFAULT 5.0,
        ACC_BUDGET FLOAT DEFAULT 0.0,
        ACC_BUDGET_REMAIN FLOAT DEFAULT 0.0,
        POOR_ZSCORE_THRESHOLD FLOAT NOT NULL DEFAULT 0.0,
        EFFECTIVE_DAYS INT(3) NOT NULL DEFAULT 7,
        MAX_CAMPAIGN_NUM INT(4) NOT NULL DEFAULT 200,
	USER_NUM_LOW INT(4) NOT NULL DEFAULT 0,
	USER_NUM_HIGH INT(4) NOT NULL DEFAULT 0,
	USER_PRIVATE_WEIGHT FLOAT NOT NULL DEFAULT 0.0,
	INTST_NUM_LOW INT(3) NOT NULL DEFAULT 0,
	INTST_NUM_HIGH INT(3) NOT NULL DEFAULT 0,
	INTST_PRIVATE_WEIGHT FLOAT NOT NULL DEFAULT 0.0,
	CNTRY_NUM_LOW INT(3) NOT NULL DEFAULT 0,
	CNTRY_NUM_HIGH INT(3) NOT NULL DEFAULT 0,
	CNTRY_PRIVATE_WEIGHT FLOAT NOT NULL DEFAULT 0.0,
	BID_LOW FLOAT NOT NULL DEFAULT 0.01,
	BID_HIGH FLOAT NOT NULL DEFAULT 0.01,
	CMP_BUDGET FLOAT NOT NULL DEFAULT 100.0,
	DLY_BUDGET FLOAT NOT NULL DEFAULT 10.0,
	PTS BOOLEAN NOT NULL DEFAULT 1,
        GENDER INT(1) NOT NULL DEFAULT 0,
	ACCELERATED_DELIVERY BOOLEAN NOT NULL DEFAULT 1,
	MONITOR_FINISHED_HOUR DATETIME,
        CONTROLLER_FINISHED_HOUR DATETIME,
        UPDATE_TIME DATETIME NOT NULL,
        DELETED BOOLEAN NOT NULL DEFAULT 0,
	FOREIGN KEY (GENDER) REFERENCES Genders(PK) ON UPDATE CASCADE
) ENGINE = INNODB, COLLATE = utf8_general_ci;

CREATE TABLE Campaigns (
        PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID INT(11) DEFAULT 0,
        NAME VARCHAR(50) DEFAULT '',
        LOCAL_STATUS INT,
        ACTIVE BOOLEAN DEFAULT '0',
        START_TIME DATETIME DEFAULT NULL,
        END_TIME DATETIME DEFAULT NULL,
        FI_ID INT,
        TOTAL_BUDGET INT DEFAULT 100,
        DAILY_BUDGET INT DEFAULT 10,
        MAX_BID FLOAT DEFAULT 0.01,
        DATA TEXT,
        TARGETED_USERS VARCHAR(1100) DEFAULT '',
        TARGETED_INTERESTS VARCHAR(660) DEFAULT '',
        LOCATIONS VARCHAR(350) DEFAULT '',
        PAC_TO_SIMILAR BOOLEAN DEFAULT 1,
        GENDER INT(1) DEFAULT 0,
        ACCELERATED_DELIVERY BOOLEAN DEFAULT 1,
	FOREIGN KEY (LOCAL_STATUS) REFERENCES Local_status(PK) ON UPDATE CASCADE,
	FOREIGN KEY (FI_ID) REFERENCES Accounts(FI_ID) ON UPDATE CASCADE,
	FOREIGN KEY (GENDER) REFERENCES Genders(PK) ON UPDATE CASCADE
) ENGINE = INNODB, COLLATE = utf8_general_ci;

CREATE TABLE Summaries (
        PK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FI_ID INT NOT NULL,
        PERIOD_START DATETIME NOT NULL,
        PERIOD_END DATETIME NOT NULL,
        TOTAL_SPEND FLOAT NOT NULL,
        TOTAL_IMPRESSIONS INT(12) NOT NULL,
        TOTAL_ENGAGEMENTS INT(12) NOT NULL,
        NEW_SPEND FLOAT NOT NULL,
        NEW_IMPRESSIONS INT(9) NOT NULL,
        NEW_ENGAGEMENTS INT(9) NOT NULL,
	FOREIGN KEY (FI_ID) REFERENCES Accounts(FI_ID) ON UPDATE CASCADE
) ENGINE = INNODB, COLLATE = utf8_general_ci;
